server:
  port: 9092

spring:
  cloud:
    gateway:
      routes:
        id: delivery-service
        uri: http://localhost:9093/
        predicates: Path=/api/orders/**
        id: provider-service
        uri: http://localhost:9094/
        predicates: Path=/api/providers/**