server:
  port: 9092

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000
   
spring:
  cloud:
    gateway:   
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: delivery-service
        uri: lb://delivery-service/
        predicates:
        - Path=/api/orders/**
      - id: provider-service
        uri: http://localhost:9094/
        predicates:
        - Path=/api/providers/**